# Generated by Django 4.1.3 on 2022-11-30 04:38

from django.db import migrations, models
import django.db.models.deletion
import django_mysql_uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "guid",
                    django_mysql_uuid.OrderedUUIDField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="UserEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.user"
                    ),
                ),
            ],
        ),
    ]
