# Generated by Django 4.1.3 on 2022-11-30 05:04

from django.db import migrations
import django_mysql_uuid
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useremail",
            name="guid",
            field=django_mysql_uuid.OrderedUUIDField(default=uuid.uuid1),
        ),
    ]
