# Generated by Django 4.1.3 on 2022-11-30 05:05

from django.db import migrations
import django_mysql_uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_useremail_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useremail",
            name="guid",
            field=django_mysql_uuid.OrderedUUIDField(),
        ),
    ]
